// deck.js
// Provides the complete 52-card deck used by the War card game.

export const cardDeck = [
  // Clubs
  { name: "Ace Club", value: 1, suit: "Clubs" },
  { name: "2 Club", value: 2, suit: "Clubs" },
  { name: "3 Club", value: 3, suit: "Clubs" },
  { name: "4 Club", value: 4, suit: "Clubs" },
  { name: "5 Club", value: 5, suit: "Clubs" },
  { name: "6 Club", value: 6, suit: "Clubs" },
  { name: "7 Club", value: 7, suit: "Clubs" },
  { name: "8 Club", value: 8, suit: "Clubs" },
  { name: "9 Club", value: 9, suit: "Clubs" },
  { name: "10 Club", value: 10, suit: "Clubs" },
  { name: "Jack Club", value: 11, suit: "Clubs" },
  { name: "Queen Club", value: 12, suit: "Clubs" },
  { name: "King Club", value: 13, suit: "Clubs" },
  // Diamonds
  { name: "Ace Diamond", value: 1, suit: "Diamonds" },
  { name: "2 Diamond", value: 2, suit: "Diamonds" },
  { name: "3 Diamond", value: 3, suit: "Diamonds" },
  { name: "4 Diamond", value: 4, suit: "Diamonds" },
  { name: "5 Diamond", value: 5, suit: "Diamonds" },
  { name: "6 Diamond", value: 6, suit: "Diamonds" },
  { name: "7 Diamond", value: 7, suit: "Diamonds" },
  { name: "8 Diamond", value: 8, suit: "Diamonds" },
  { name: "9 Diamond", value: 9, suit: "Diamonds" },
  { name: "10 Diamond", value: 10, suit: "Diamonds" },
  { name: "Jack Diamond", value: 11, suit: "Diamonds" },
  { name: "Queen Diamond", value: 12, suit: "Diamonds" },
  { name: "King Diamond", value: 13, suit: "Diamonds" },
  // Hearts
  { name: "Ace Heart", value: 1, suit: "Hearts" },
  { name: "2 Heart", value: 2, suit: "Hearts" },
  { name: "3 Heart", value: 3, suit: "Hearts" },
  { name: "4 Heart", value: 4, suit: "Hearts" },
  { name: "5 Heart", value: 5, suit: "Hearts" },
  { name: "6 Heart", value: 6, suit: "Hearts" },
  { name: "7 Heart", value: 7, suit: "Hearts" },
  { name: "8 Heart", value: 8, suit: "Hearts" },
  { name: "9 Heart", value: 9, suit: "Hearts" },
  { name: "10 Heart", value: 10, suit: "Hearts" },
  { name: "Jack Heart", value: 11, suit: "Hearts" },
  { name: "Queen Heart", value: 12, suit: "Hearts" },
  { name: "King Heart", value: 13, suit: "Hearts" },
  // Spades
  { name: "Ace Spade", value: 1, suit: "Spades" },
  { name: "2 Spade", value: 2, suit: "Spades" },
  { name: "3 Spade", value: 3, suit: "Spades" },
  { name: "4 Spade", value: 4, suit: "Spades" },
  { name: "5 Spade", value: 5, suit: "Spades" },
  { name: "6 Spade", value: 6, suit: "Spades" },
  { name: "7 Spade", value: 7, suit: "Spades" },
  { name: "8 Spade", value: 8, suit: "Spades" },
  { name: "9 Spade", value: 9, suit: "Spades" },
  { name: "10 Spade", value: 10, suit: "Spades" },
  { name: "Jack Spade", value: 11, suit: "Spades" },
  { name: "Queen Spade", value: 12, suit: "Spades" },
  { name: "King Spade", value: 13, suit: "Spades" },
];
